apiVersion: v1
kind: ConfigMap
metadata:
  name: samyam-config
  namespace: default
data:
  VITE_FASTAPI_URL: "http://ai-engine-service:8000"
  PORT: "8000"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
